services:
  postgres:
    image: postgres:16
    container_name: tacos-manager-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tacosmanager
      POSTGRES_PASSWORD: tacosmanager
      POSTGRES_DB: tacosmanagerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: